# Generated by Django 3.1.3 on 2020-11-25 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0002_auto_20201124_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=50)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('floors', models.IntegerField()),
                ('land_size', models.IntegerField()),
                ('parkings', models.IntegerField()),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Apartment', 'Apartment')], default='House', max_length=50)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_4', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_5', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_6', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_7', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_8', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_9', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_10', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_11', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_12', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_13', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_14', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_15', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_16', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_17', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_18', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_19', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_20', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
